// src/webscraping/config/teamConfig.js

export default [
	{
		name: "Atletico-Mineiro",
		betsapiId: "1313",
		urlPath: "/ts/1313/Atletico-Mineiro/",
		geName: "atletico-mg",
		ondeAssistirName: "atletico-mineiro",
	},
	{
		name: "Bahia",
		betsapiId: "165469",
		urlPath: "/ts/165469/Bahia/",
		geName: "bahia",
		ondeAssistirName: "bahia",
	},
	{
		name: "Botafogo",
		betsapiId: "2051",
		urlPath: "/ts/2051/Botafogo/",
		geName: "botafogo",
		ondeAssistirName: "botafogo",
	},
	{
		name: "Bragantino",
		betsapiId: "3165",
		urlPath: "/ts/3165/Bragantino/",
		geName: "bragantino",
		ondeAssistirName: "bragantino",
	},
	{
		name: "Ceara",
		betsapiId: "1264",
		urlPath: "/ts/1264/Ceara/",
		geName: "ceara",
		ondeAssistirName: "ceara",
	},
	{
		name: "Corinthians",
		betsapiId: "4128",
		urlPath: "/ts/4128/Corinthians/",
		geName: "corinthians",
		ondeAssistirName: "corinthians",
	},
	{
		name: "Cruzeiro",
		betsapiId: "577",
		urlPath: "/ts/577/Cruzeiro/",
		geName: "cruzeiro",
		ondeAssistirName: "cruzeiro",
	},
	{
		name: "Flamengo",
		betsapiId: "1339",
		urlPath: "/ts/1339/Flamengo/",
		geName: "flamengo",
		ondeAssistirName: "flamengo",
	},
	{
		name: "Fluminense",
		betsapiId: "1286",
		urlPath: "/ts/1286/Fluminense/",
		geName: "fluminense",
		ondeAssistirName: "fluminense",
	},
	{
		name: "Fortaleza",
		betsapiId: "43589",
		urlPath: "/ts/43589/Fortaleza/",
		geName: "fortaleza",
		ondeAssistirName: "fortaleza",
	},
	{
		name: "Gremio",
		betsapiId: "1312",
		urlPath: "/ts/1312/Gremio/",
		geName: "gremio",
		ondeAssistirName: "gremio",
	},
	{
		name: "Internacional",
		betsapiId: "1422",
		urlPath: "/ts/1422/Internacional/",
		geName: "internacional",
		ondeAssistirName: "internacional",
	},
	{
		name: "Juventude",
		betsapiId: "45589",
		urlPath: "/ts/45589/Juventude/",
		geName: "juventude",
		ondeAssistirName: "juventude",
	},
	{
		name: "Mirassol",
		betsapiId: "8555",
		urlPath: "/ts/8555/Mirassol/",
		geName: "mirassol",
		ondeAssistirName: "mirassol",
	},
	{
		name: "Palmeiras",
		betsapiId: "1287",
		urlPath: "/ts/1287/Palmeiras/",
		geName: "",
		ondeAssistirName: "",
	},
	{
		name: "Santos",
		betsapiId: "579",
		urlPath: "/ts/579/Santos/",
		geName: "palmeiras",
		ondeAssistirName: "palmeiras",
	},
	{
		name: "Sao Paulo",
		betsapiId: "1314",
		urlPath: "/ts/1314/Sao Paulo/",
		geName: "sao-paulo",
		ondeAssistirName: "sao-paulo",
	},
	{
		name: "Sport-Recife",
		betsapiId: "1421",
		urlPath: "/ts/1421/Sport-Recife/",
		geName: "sport",
		ondeAssistirName: "sport",
	},
	{
		name: "Vasco-da-Gama",
		betsapiId: "56101",
		urlPath: "/ts/56101/Vasco-da-Gama/",
		geName: "vasco",
		ondeAssistirName: "vasco-da-gama",
	},
	{
		name: "Vitoria",
		betsapiId: "1419",
		urlPath: "/ts/1419/Vitoria/",
		geName: "vitoria",
		ondeAssistirName: "vitoria",
	},
];
