export interface CookieOptions {
  maxAgeSeconds?: number;
  path?: string;
  domain?: string;
  secure?: boolean;
  httpOnly?: boolean;
  sameSite?: "Lax" | "Strict" | "None";
}

/** The cookies on a request, by name. A malformed pair is skipped, never thrown on. */
export function parseCookies(header: string | undefined): Record<string, string> {
  const cookies: Record<string, string> = {};
  if (!header) return cookies;
  for (const pair of header.split(";")) {
    const separator = pair.indexOf("=");
    if (separator < 1) continue;
    const name = pair.slice(0, separator).trim();
    if (name === "") continue; // " =x": the separator check ran before the trim
    const raw = pair.slice(separator + 1).trim();
    try {
      cookies[name] = decodeURIComponent(raw);
    } catch {
      // an undecodable value is just not a cookie we set
    }
  }
  return cookies;
}

// A cookie name or attribute value carrying ; , CR or LF could break out of
// the header into other attributes or other headers. Every value here is
// generated by this code, so this is a guard against a future caller, not a
// reaction to a present bug.
const UNSAFE = /[;,\r\n\s]/;

export function serializeCookie(name: string, value: string, options: CookieOptions = {}): string {
  if (UNSAFE.test(name)) throw new Error(`Invalid cookie name: ${name}`);
  if (options.domain && UNSAFE.test(options.domain)) throw new Error("Invalid cookie domain");
  if (options.path && UNSAFE.test(options.path)) throw new Error("Invalid cookie path");

  const parts = [`${name}=${encodeURIComponent(value)}`];
  parts.push(`Path=${options.path ?? "/"}`);
  if (options.domain) parts.push(`Domain=${options.domain}`);
  if (options.maxAgeSeconds !== undefined) parts.push(`Max-Age=${Math.floor(options.maxAgeSeconds)}`);
  if (options.httpOnly !== false) parts.push("HttpOnly");
  if (options.secure) parts.push("Secure");
  parts.push(`SameSite=${options.sameSite ?? "Lax"}`);
  return parts.join("; ");
}

/** A header that removes a cookie: same name, path and domain it was set with, already expired. */
export function clearCookie(name: string, options: Pick<CookieOptions, "path" | "domain" | "secure"> = {}): string {
  return serializeCookie(name, "", { ...options, maxAgeSeconds: 0 });
}
