export const MAPEAMENTO_CANAIS = {
  band: "band",
  bandeirantes: "band",
  "band sports": "band",
  cazetv_youtube: "cazetv",
  disney: "disneyplus",
  "disney+": "disneyplus",
  disney_plus: "disneyplus",
  "disney-plus": "disneyplus",
  "star+": "disneyplus",
  espn: "espn",
  "espn brasil": "espn",
  "espn+": "espn",
  globo: "globo",
  globoplay: "globoplay",
  goat: "goat",
  "nosso futebol": "nossofutebol",
  "nosso-futebol": "nossofutebol",
  nosso_futebol: "nossofutebol",
  paramount: "paramountplus",
  paramountplus: "paramountplus",
  "paramount-plus": "paramountplus",
  "paramount plus": "paramountplus",
  paramount_plus: "paramountplus",
  "paramount+": "paramountplus",
  premiere: "premiere",
  "premiere fc": "premiere",
  "premiere canal": "premiere",
  premiere_canal: "premiere",
  prime: "primevideo",
  "prime-video": "primevideo",
  prime_video: "primevideo",
  "prime video": "primevideo",
  "record-tv": "record",
  "record tv": "record",
  record_tv: "record",
  recordtv: "record",
  record: "record",
  sbt: "sbt",
  "sbt tv": "sbt",
  "sportv 2": "sportv",
  "sportv 3": "sportv",
  tnt: "tntsports",
  tnt_sports: "tntsports",
  "tnt-sports": "tntsports",
  "tnt sports": "tntsports",
  youtube: "youtube",
};
